version: '3.8'
services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - '5432:5432'
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: party-radar
    volumes:
      - ./.db:/var/lib/postgresql/data
    healthcheck:
        test: [ 'CMD-SHELL', 'pg_isready', '-U', 'postgres', '-d', 'party-radar' ]
        interval: 1s
        timeout: 5s
        retries: 10

  api:
    image: party-radar/backend
    container_name: api
    build: ./
    env_file: .env
    ports:
      - '8080:8080'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/api/v1/healthcheck || exit 1
      interval: 5s
      retries: 5
      timeout: 10s
    depends_on:
      db:
        condition: service_healthy
    command: [ "sh", "-c", "./migration up && ./api" ]