// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class ProdFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbK7wRBFtkv_6tj088IzTSF7M7gO_rJgA',
    appId: '1:1048334599741:android:a0b82f719ccdf0b0234c54',
    messagingSenderId: '1048334599741',
    projectId: 'party-radar-prod',
    storageBucket: 'party-radar-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzRA1CCVJNaMP34kdJUYIJeFEeWvxDTS8',
    appId: '1:1048334599741:ios:f942209e7acef7f8234c54',
    messagingSenderId: '1048334599741',
    projectId: 'party-radar-prod',
    storageBucket: 'party-radar-prod.appspot.com',
    androidClientId: '1048334599741-sahbkjdbm4hru6brdog6753r2evj8n27.apps.googleusercontent.com',
    iosClientId: '1048334599741-61s18i1e8el4n4pgafejucofntcnt6i1.apps.googleusercontent.com',
    iosBundleId: 'app.party-radar',
  );
}
