name: Backup service deployment

run-name: Deploy backup service on ${{ github.ref_name }}

on:
  workflow_dispatch:
  push:
    paths:
      - "infrastructure/backup/**"

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create backup.env file
        run: |
          echo "${{ secrets.BACKUP_ENV }}" > infrastructure/backup/backup.env

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          overwrite: true
          source: infrastructure/backup/backup.env,infrastructure/backup/docker-compose.yaml
          target: ~/

      - name: Deploy to Hel server via SSH action
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: |
            docker compose -f infrastructure/backup/docker-compose.yaml down
            docker compose -f infrastructure/backup/docker-compose.yaml up -d
