name: (BE) Build + publish (+ deploy)

run-name: (BE) Build + publish (+ deploy) ${{ github.ref_name }}

on:
  push:
    paths:
      - "backend/**"
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Environment
        options:
          - dev
          - prod

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/backend-${{ inputs.choice || 'dev' }}

jobs:
  build_and_publish:
    permissions:
      contents: read
      packages: write
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Create serviceAccountKey.json file
        id: create-json
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "serviceAccountKey.json"
          json: ${{ secrets[format('{0}_SERVICE_ACCOUNT_KEY', (inputs.choice || 'dev'))] }}
          dir: "backend/"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.3.0
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  auto-deploy:
    uses: ./.github/workflows/be-deploy.yaml
    needs: build_and_publish
    if: github.ref == 'refs/heads/main'
    secrets: inherit
    with:
      choice: ${{ inputs.choice || 'dev' }}