name: (BE) Deploy

run-name: (BE) Deploy ${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      choice:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Environment
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: self-hosted
    env:
      REGISTRY: ghcr.io
      CONTAINER_NAME: api-${{ inputs.choice }}
      IMAGE_NAME: "ghcr.io/${{ github.repository }}/backend:${{ github.ref_name }}"
      ENVIRONMENT: ${{ inputs.choice }}
    steps:
      - name: Create .env file
        run: |
          echo "${{ secrets[format('{0}_ENV_FILE', inputs.choice)] }}" > backend/.env

      - name: Create serviceAccountKey.json file
        id: create-json
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "serviceAccountKey.json"
          json: ${{ secrets[format('{0}_SERVICE_ACCOUNT_KEY', inputs.choice)] }}
          dir: ${{ inputs.choice }}/backend/

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          overwrite: true
          source: backend/.env,backend/docker-compose.${{ inputs.choice }}.yaml
          target: ~/${{ inputs.choice }}/

      - name: Deploy to Hel server via SSH action
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          envs: CONTAINER_NAME, {{ github.actor }}, {{ secrets.GITHUB_TOKEN }}, {{ env.REGISTRY }}, IMAGE_NAME
          script: |
            docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}
            docker pull $IMAGE_NAME
            docker container rm -f $CONTAINER_NAME
            docker compose -f ${{ inputs.choice }}/backend/docker-compose.${{ inputs.choice }}.yaml -p ${{ inputs.choice }} up -d
