name: (BE) Deploy

run-name: (BE) Deploy ${{ github.ref_name }}

on: [workflow_call, workflow_dispatch]

jobs:
  deploy:
    runs-on: self-hosted
    env:
      REGISTRY: ghcr.io
      CONTAINER_NAME: "party-radar_be_dev"
      IMAGE_NAME: "ghcr.io/${{ github.repository }}/backend:${{ github.ref_name }}"
    steps:
      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > backend/.env

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          overwrite: true
          source: "backend/.env,backend/docker-compose.dev.yaml"
          target: ~/

      - name: Deploy to Hel server via SSH action
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          envs: CONTAINER_NAME, {{ github.actor }}, {{ secrets.GITHUB_TOKEN }}, {{ env.REGISTRY }}, IMAGE_NAME
          script: |
            docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}
            docker pull $IMAGE_NAME
            docker container rm -f $CONTAINER_NAME
            docker compose -f backend/docker-compose.dev.yaml up -d
