name: (BE) Deploy

run-name: (BE) Deploy ${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      choice:
        required: true
        type: string
  workflow_dispatch:
    choice:
      type: choice
      description: Environment
      options:
        - dev
        - prod

jobs:
  deploy:
    runs-on: self-hosted
    env:
      REGISTRY: ghcr.io
      CONTAINER_NAME: api-${{ github.event.inputs.choice }}
      IMAGE_NAME: "ghcr.io/${{ github.repository }}/backend:${{ github.ref_name }}"
      ENVIRONMENT: ${{ github.event.inputs.choice }}
    steps:
      - name: Create .env file
        run: |
          echo "${{ secrets[format('{0}_ENV_FILE', github.event.inputs.choice)] }}" > backend/.env

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          overwrite: true
          source: backend/.env,backend/docker-compose.${{ github.event.inputs.choice }}.yaml
          target: ~/${{ github.event.inputs.choice }}/

      - name: Deploy to Hel server via SSH action
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          envs: CONTAINER_NAME, {{ github.actor }}, {{ secrets.GITHUB_TOKEN }}, {{ env.REGISTRY }}, IMAGE_NAME
          script: |
            docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}
            docker pull $IMAGE_NAME
            docker container rm -f $CONTAINER_NAME
            docker compose -f ${{ github.event.inputs.choice }}/backend/docker-compose.${{ github.event.inputs.choice }}.yaml up -d
